Jumpscale/prefab9

JumpScale9Prefab/apps/PrefabPortal.py
be consistent and use force_oauth_instance in config and the same for portal.
=> use force_oauth_instance

JumpScale9Prefab/PrefabCore.py
don't replace the method with a string during the call
=> fix prefab.core.cd

JumpScale9Prefab/PrefabSSH.py
* chmod the keys generated by keygen to be 600 to allow adding it to agent
* allow ssh-add -l die to be false to prevent errors in case there is no keys are loaded
=> Fix prefab ssh client

JumpScale9Prefab/apps/PrefabPortal.py
remove a couple of the duplicate deps that was causing conflict in packages versions.
-
-
**Version**: 
**Fixes**: #
=> remove duplicate dependencies

JumpScale9Prefab/apps/PrefabIssueManager.py
Prefab for installing issuemanager
=> prefabissuemanager

JumpScale9Prefab/apps/PrefabPortal.py
Revisiting portal installation and changing installation to install portal package.
**Version**: 9.1.1
**Fixes**: #https://github.com/Jumpscale/prefab9/issues/24
=> Prefab portal

JumpScale9Prefab/PrefabCore.py
-
-
**Version**: 
**Fixes**:  
Jumpscale/developer#73 
zero-os/0-orchestrator#731
=> Set HOME env variable if not exist 

JumpScale9Prefab/apps/PrefabAtYourService.py
=> update ays module to add ays space to portal

JumpScale9Prefab/systemservices/PrefabDocker.py
-
-
**Version**: 
**Fixes**: Jumpscale/ays9#232
=> Fix prefab docker 

JumpScale9Prefab/apps/PrefabPostgresql.py
Updates for prefabPostgres
- Configurable password/dbdir
- Start in tmux
- Stop updated
=> postgresprefab updates

JumpScale9Prefab/apps/PrefabCaddy.py
-
-
**Version**: 
**Fixes**: #39
=> Fix prefab caddy module

JumpScale9Prefab/apps/PrefabCaddy.py
-
-
**Version**: 
**Fixes**: #
=> Fix caddyman git url for caddyprefab module

JumpScale9Prefab/apps/PrefabCrm.py
-
-
**Version**: 
**Fixes**: incubaid/crm#35
=> Add Prefab module to install crm 

JumpScale9Prefab/apps/PrefabPostgresql.py
-
-
**Version**: 
**Fixes**: #
=> Wait for PrefabPostgres to start before updating password

JumpScale9Prefab/apps/PrefabCrm.py, JumpScale9Prefab/apps/PrefabPostgresql.py
-
-
**Version**: 
**Fixes**: incubaid/crm#35
=> Add more options and fixes to crm install 

JumpScale9Prefab/apps/PrefabCelery.py
**Fixes**: #https://github.com/Jumpscale/prefab9/issues/45
=> prefab module for celery

JumpScale9Prefab/apps/PrefabCrm.py
-
-
**Version**: 
**Fixes**: #
=> Add mods for crm prefab module

JumpScale9Prefab/PrefabPackage.py
**Fixes**: https://github.com/Jumpscale/prefab9/issues/48
=> prefab clean remove behaviour

JumpScale9Prefab/apps/PrefabCaddy.py, JumpScale9Prefab/apps/PrefabCrm.py
-
-
**Version**: 
**Fixes**: #
=> Add tls option for crm prefab module

JumpScale9Prefab/apps/PrefabNoVNC.py
Created aorefab for noVNC
-
-
**Version**: 
**Fixes**: #
=> Add a prefab for gigforks/noVNC .

JumpScale9Prefab/PrefabCore.py
=> re-enabling prefab core sudomode

JumpScale9Prefab/apps/PrefabAtYourService.py
https://github.com/Jumpscale/ays9/issues/348
- prefab ays start takes more params so it can be used within the ays repo cmd
-
**Version**: 
**Fixes**: #
=> adjusted the start of ays to take more params

JumpScale9Prefab/apps/PrefabAtYourService.py
unfinshed changes in prefabays 
-
-
**Version**: 
**Fixes**: #
=> requested adjustments

JumpScale9Prefab/apps/PrefabAtYourService.py
Installation of ays using prefab fix.
=> fix for prefab ays

JumpScale9Prefab/PrefabCore.py, JumpScale9Prefab/PrefabLoader.py, modules/network/PrefabVRouter.py, modules/web/PrefabPortal.py
Related to https://github.com/Jumpscale/core9/pull/94
Vresion: 9.3.0
=> Nofs install

modules/web/PrefabPortal.py
Configuring portal using prefab
=> new portal config file

JumpScale9Prefab/PrefabBase.py, modules/js9/Prefabjs9Core.py, modules/web/PrefabPortal.py
- Fixing `doneSet` write to `state.toml`
- Removing unneeded portal module code
=> fixes for prefab base

JumpScale9Prefab/apps/PrefabAtYourService.py
**Fixes**: https://github.com/Jumpscale/ays9/issues/381
=> fix ays start

modules/web/PrefabPortal.py
installing more than one portal through prefab
**Version**: 
9.3.0
=> add support for installing more than one portal

modules/db/PrefabPostgresql.py, modules/network/PrefabZerotier.py
Fixes for Zerotier and PostgreSql Modules
**Version**: 9.3.0
=> Prefab modules

modules/js9/PrefabAtYourService.py
Signed-off-by: Khaled K. Badr <khaledkbadr@outlook.com>
- There was no way to configure ays api console from ays prefab. this pr adds a way to do it
-  Add configure_api_console method to ays prefab which allows changing host/port of the ays api console
**Version**:  9.3.0
**Fixes**: #99
=> add configure_api_console method to ays prefab

modules/js9/Prefabjs9Core.py
**Fixes**: #https://github.com/Jumpscale/prefab9/issues/116
=> fix js9core.install

docs/prefab.kubernetes.md, modules/system/PrefabProcessManager.py, modules/system/PrefabSSH.py, modules/virtualization/PrefabKubernetes.py
https://github.com/0-complexity/openvcloud_installer/issues/18
- refactoring in the kubernetes to allow 
**Version**: 
**Fixes**: #
=> refactored and rewrote prefabK8s to be HA

JumpScale9Prefab/PrefabCore.py, docs/prefab.kubernetes.md, docs/prefab.virtualization.md, modules/runtimes/PrefabGolang.py, modules/system/PrefabProcessManager.py, modules/system/PrefabSSH.py, modules/virtualization/PrefabDocker.py, modules/virtualization/PrefabKubernetes.py
issue #57 
- added kubernetes prefab module to install and deploy a prefab
**Version**: 
**Fixes**: #
=> 9.3.0 kubernetes

modules/system/PrefabGroup.py, modules/system/PrefabUser.py
=> Fixes for PrefabGroup and PrefabUser

modules/virtualization/PrefabKubernetes.py
Kubernetes client install method
=> add install client method for kubernetes

modules/virtualization/PrefabKubernetes.py
adjustment to prefab, fixes and cleaner code
- more separation for  the functions 
- added some bug fixes to the to allow mounting of secrets and config maps 
- fixed the version to 1.8.5
**Version**: 
**Fixes**: #
=> 9.3.0 kubernetes granulizing

modules/virtualization/PrefabKubernetes.py
=> K8s install fix

modules/network/PrefabZerotier.py
fix bug of network name space   #201
=> fix bug of network name space #201
